name: build

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  attestations: write
  packages: write

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        id: build
        uses: docker/build-push-action
      - name: Generate SBOM attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ghpages
          subject-digest: ${{ steps.build.outputs.digest }}
